### PR TITLE
Add LLVMBoostrap 11.0.1

### PR DESCRIPTION
**Pull request by omus**
Ref: https://github.com/JuliaPackaging/Yggdrasil/pull/2473

### CODE REVIEW

**Comment by giordano** [comment]
Can you please also update the [list of available llvm versions](https://github.com/JuliaPackaging/BinaryBuilderBase.jl/blob/940ce9b5e0844721468cf72ecdd3f4ebd039ad61/src/Rootfs.jl#L376)?

**Comment by giordano** [comment]
Test failures don't look good:
```
Compilation - macOS x86_64: Test Failed at /home/runner/work/BinaryBuilderBase.jl/BinaryBuilderBase.jl/test/runners.jl:104
  Expression: (split(String(read(iobuff)), "\n"))[2] == ""
   Evaluated: "error: unknown target CPU 'x86-64'" == ""
Stacktrace:
 [1] (::var"#199#214"{Platform})(dir::String)
   @ Main ~/work/BinaryBuilderBase.jl/BinaryBuilderBase.jl/test/runners.jl:104
 [2] mktempdir(fn::var"#199#214"{Platform}, parent::String; prefix::String)
   @ Base.Filesystem ./file.jl:713
 [3] mktempdir(fn::Function, parent::String)
   @ Base.Filesystem ./file.jl:711
 [4] macro expansion
   @ ~/work/BinaryBuilderBase.jl/BinaryBuilderBase.jl/test/runners.jl:99 [inlined]
 [5] macro expansion
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1221 [inlined]
 [6] macro expansion
   @ ~/work/BinaryBuilderBase.jl/BinaryBuilderBase.jl/test/runners.jl:98 [inlined]
 [7] macro expansion
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1146 [inlined]
 [8] top-level scope
   @ ~/work/BinaryBuilderBase.jl/BinaryBuilderBase.jl/test/runners.jl:32

[...]

Compilation - FreeBSD x86_64: Test Failed at /home/runner/work/BinaryBuilderBase.jl/BinaryBuilderBase.jl/test/runners.jl:104
  Expression: (split(String(read(iobuff)), "\n"))[2] == ""
   Evaluated: "error: unknown target CPU 'x86-64'" == ""
Stacktrace:
 [1] (::var"#199#214"{Platform})(dir::String)
   @ Main ~/work/BinaryBuilderBase.jl/BinaryBuilderBase.jl/test/runners.jl:104
 [2] mktempdir(fn::var"#199#214"{Platform}, parent::String; prefix::String)
   @ Base.Filesystem ./file.jl:713
 [3] mktempdir(fn::Function, parent::String)
   @ Base.Filesystem ./file.jl:711
 [4] macro expansion
   @ ~/work/BinaryBuilderBase.jl/BinaryBuilderBase.jl/test/runners.jl:99 [inlined]
 [5] macro expansion
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1221 [inlined]
 [6] macro expansion
   @ ~/work/BinaryBuilderBase.jl/BinaryBuilderBase.jl/test/runners.jl:98 [inlined]
 [7] macro expansion
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1146 [inlined]
 [8] top-level scope
   @ ~/work/BinaryBuilderBase.jl/BinaryBuilderBase.jl/test/runners.jl:32
```
and since this happens for macOS and FreeBSD which use LLVM by default, this is likely a real issue

**Comment by omus** [comment]
I'm unable to reproduce locally when using `BINARYBUILDER_FULL_SHARD_TEST=true`. I'll restart the CI just to ensure the issue is reproducible here at least.

**Comment by omus** [comment]
I deleted my local copies of the LLVMBootstrap 11 artifacts and noticed they weren't re-downloaded during these tests. I suspect this is an unrelated failure.

**Comment by omus** [comment]
🎉  I've managed to reproduce the issue locally. My local branch and pushed branch were out of sync

**Comment by giordano** [comment]
> My local branch and pushed branch were out of sync

That's an interesting situation :smile:

**Comment by omus** [comment]
After some experimentation I found that LLVM 10.0.1 doesn't have this problem while LLVM 11.0.0 does. Performing a bisect I found that https://github.com/llvm/llvm-project/commit/3537939cda86f0b5b06233eb99ddc9eb22935008 is the first commit that produces the issue.

**Comment by giordano** [comment]
Good detective job! :+1:

**Comment by vchuravy** [comment]
> that LLVM 10.0.1 doesn't have this problem while LLVM 11.0.0 does. 

I assume you meant the inverse?

**Comment by omus** [comment]
After reviewing the failing commit and further changes I discovered https://github.com/llvm/llvm-project/commit/9ecda9aa804dcb49e30e46161b29976494b0a1f9 ([llvm-commits thread](https://lists.llvm.org/pipermail/llvm-commits/Week-of-Mon-20200706/804078.html)) which mentions:

> It gets miscompiled with GCC 5.3, causing Clang to crash with
"error: unknown target CPU 'x86-64'"

Testing with GCC 10.2 seems to have solved the issue. I'll determine the lowest version I can use.

Note: The commit above references repro

**Comment by giordano** [comment]
I don't understand: isn't that patch in our source code?  Shouldn't it solve the issue with GCC 5?

**Comment by vchuravy** [comment]
Aren't we using musl GCC for bootstrapping?

**Comment by omus** [comment]
> I don't understand: isn't that patch in our source code? Shouldn't it solve the issue with GCC 5?

You are correct that the patch I mentioned is included in LLVM 11.0.1. I believe there is another issue present that hasn't been solved which can be worked around by using a newer GCC.

> Aren't we using musl GCC for bootstrapping?

Originally I thought we were using the system musl GCC for bootstrapping LLVMBootstrap. However, when I encountered an error [stating that GCC 5.1+ was required](https://github.com/JuliaPackaging/Yggdrasil/pull/2473#discussion_r567199650) I used `preferred_gcc_version` to correct the problem which means GCCBootstrap is being used.

**Comment by omus** [comment]
Quick status update:
- Using GCCBoostrap@5.2 can be used to successfully build LLVMBootstrap@11.0.1 but has the `unknown target CPU` under certain environments
- Using GCCBootstrap@6.1 fails to build LLVMBootstrap@11.0.1 at the 50% mark (I didn't look into this further)
- Using GCCBootstrap@7.1 builds LLVMBootstrap@11.0.1 and doesn't have the unknown target error on `x86_64-apple-darwin` or `x86_64-linux-musl`.

**Comment by omus** [comment]
Using new LLVMBootstrap@11.0.1 deployment which should fix the issue we were seeing

**Comment by giordano** [comment]
Note: before merging this I'd like to run the tests in BinaryBuilder as well

**Comment by giordano** [comment]
It looks all good, thank you so much @omus for the great work!

**Pull request merged**
