### PR TITLE
Add GCC 13.2 shards to BB

### PR DESCRIPTION
**Pull request by gbaraldi**

### CODE REVIEW

**Comment by gbaraldi** [comment]
Is this mergeable?

**Comment by giordano** [comment]
I'd still like to see the corresponding PR in Yggdrasil, I don't like merging PRs here if we don't have the companion too

**Comment by giordano** [comment]
BTW, I think we should first get #318 merged.  @staticfloat any reason why that hasn't been done yet?

**Comment by staticfloat** [comment]
Nope, just crazy busy.  Sorry.

**Comment by gbaraldi** [comment]
Do I need to rebuild then?

**Comment by giordano** [comment]
If you were after https://github.com/JuliaPackaging/Yggdrasil/pull/7136 on Yggdrasil, you should be good.

**Pull request merged**
