### PR TITLE
Update Go shard to include gofmt

### PR DESCRIPTION
**Pull request by omus**
x-ref: https://github.com/JuliaPackaging/Yggdrasil/pull/2795

### CODE REVIEW

**Comment by omus** [comment]
Hmm, in using this shard locally I'm seeing `gofmt` but it's not installed on the `PATH`. Did I miss something?

**Comment by giordano** [comment]
> Hmm, in using this shard locally I'm seeing gofmt but it's not installed on the PATH. Did I miss something?

Where is it?  `PATH` is set in
https://github.com/JuliaPackaging/BinaryBuilderBase.jl/blob/d37e9c4e50a7ce3ec983285a9c7f94bc96f83098/src/Runner.jl#L877-L891
and it can be tweaked if necessary, but it'd be good to not have to edit it.

**Comment by omus** [comment]
`gofmt` locations:
```
/workspace/.mounts/Go.v1.16.3.x86_64-linux-musl.squashfs/go/bin/gofmt
/workspace/.mounts/Go.v1.16.3.x86_64-linux-musl.squashfs/go/src/cmd/gofmt
/opt/x86_64-linux-musl/go/bin/gofmt
/opt/x86_64-linux-musl/go/src/cmd/gofmt
```
The `go` command is on the path via `/opt/bin/x86_64-linux-musl-libgfortran3-cxx03/go`. I'm curious how it got there...

**Comment by giordano** [comment]
I guess because of https://github.com/JuliaPackaging/Yggdrasil/blob/980dfb2ab0a3ed7fe35c7e1c4f1e6ea4cf3e1903/0_RootFS/Go/build_tarballs.jl#L18?

**Comment by omus** [comment]
I think I figured it out. I'll update this PR shortly

**Comment by omus** [comment]
@staticfloat would be good for you to check this is the right way to do it

**Comment by giordano** [comment]
Oh, that was the wrapper, right :smile:

**Comment by staticfloat** [comment]
Looks good to me!  Thanks as always, @omus

**Pull request merged**
