### PR TITLE
Add support for FreeBSD AArch64

### PR DESCRIPTION
**Pull request by ararslan**
Accompanying Yggdrasil PR: https://github.com/JuliaPackaging/Yggdrasil/pull/9220

I'll flip this out of draft mode once all compilers have been built.

### CODE REVIEW

**Comment by giordano** [comment]
With reference to https://github.com/JuliaPackaging/Yggdrasil/pull/9220#issuecomment-2284551377, for gcc I was thinking of https://github.com/JuliaPackaging/BinaryBuilderBase.jl/blob/56580d9a65804071e2d3626b82283f5978ac8d14/src/Rootfs.jl#L578-L584 but that was specific to aarch64-darwin where we have a different toolchain version number under the hood (the user doesn't need to know it), but this may just work for aarch64-freebsd https://github.com/JuliaPackaging/BinaryBuilderBase.jl/blob/56580d9a65804071e2d3626b82283f5978ac8d14/src/Rootfs.jl#L586-L593

However, if we only have GCC >= 7, you probably need to adapt https://github.com/JuliaPackaging/BinaryBuilderBase.jl/blob/56580d9a65804071e2d3626b82283f5978ac8d14/src/Rootfs.jl#L763-L770 gcc 7 has libgfortran v4, so you have to exclude v3

**Comment by giordano** [comment]
Reminder: you'll need to add aarch64-freebsd to the list of platforms incompatible with Julia v1.5 at https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/8aadff4c54e12a31fe605defd81d99da78c60af2/src/AutoBuild.jl#L199

**Comment by ararslan** [comment]
Ah thank you! PR: https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/1342

**Comment by ararslan** [comment]
I also bumped the version so that we can tag a new release.

**Review by giordano — APPROVED** [review]

**Pull request merged**
