### PR TITLE
Use `-mtune=generic` for `x84-64` microarchitecture

### PR DESCRIPTION
**Pull request by giordano**

### CODE REVIEW

**Comment by staticfloat** [comment]
`x84-64` 😂

**Comment by giordano** [comment]
Look at the branch name :sweat_smile:

**Comment by staticfloat** [comment]
`x64-64` == `x`? ;)

**Comment by StefanKarpinski** [comment]
Your math is a bit rust, @staticfloat, that should be `(x-1)64`.

**Comment by staticfloat** [comment]
And here I never thought I’d need to do algebra again after leaving school....

**Pull request merged**
